AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudSAMTemplates/notification/eventbridge creates Amazon EventBridge to support events from AWS Services.

Parameters:
  LogicalNamePrefix:
    Type: String
    Default: Notification-
    AllowedPattern: .+
    Description: Custom prefix name [required]
  HealthEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about Health Events [required]
  ScheduledEventsRule:
    Type: String
    Default: DISABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about Scheduled Events [required]
  EBSEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about EBS [required]
  AutoScalingEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about AutoScaling [required]
  EC2EventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about EC2 [required]
  ECSTaskEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about ECS Task [required]
  KMSEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about KMS [required]
  ManagementConsoleEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about Management Console [required]
  TagEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about Tag [required]
  TrustedAdvisorEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about Trusted Advisor [required]
  RDSEventsRule:
    Type: String
    Default: ENABLED
    AllowedValues:
     - ENABLED
     - DISABLED
    Description: Enable or disable the events rule about RDS [required]
  SNSForAlertArn:
    Type: String
    Default: ''
    Description: Amazon SNS Topic ARN for alert
  

Resources:
  HealthEvents:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Health Events created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.health
        detail-type: 
          - AWS Health Event
      Name: !Sub ${LogicalNamePrefix}-HealthEvents
      State: !Ref HealthEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForScheduledEvents:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Scheduled Events created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.events
        detail-type: 
          - Scheduled Event
      Name: !Sub ${LogicalNamePrefix}-ScheduledEvents
      State: !Ref ScheduledEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForEBS:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for EBS created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.ec2
        detail-type: 
          - EBS Volume Notification
          - EBS Snapshot Notification
          - EBS Multi-Volume Snapshots Completion Status
          - EBS Fast Snapshot Restore State-change Notification
      Name: !Sub ${LogicalNamePrefix}-EBS
      State: !Ref EBSEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForAutoScaling:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for AutoScaling created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.autoscaling
        detail-type: 
          - EC2 Instance-launch Lifecycle Action
          - EC2 Instance Launch Successful
          - EC2 Instance Launch Unsuccessful
          - EC2 Instance-terminate Lifecycle Action
          - EC2 Instance Terminate Successful
          - EC2 Instance Terminate Unsuccessful
      Name: !Sub ${LogicalNamePrefix}-AutoScaling
      State: !Ref AutoScalingEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForEC2:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for EC2 created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.ec2
        detail-type: 
          - EC2 Instance State-change Notification
      Name: !Sub ${LogicalNamePrefix}-EC2
      State: !Ref EC2EventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForECSTask:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for ECS created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.ecs
        detail-type: 
          - ECS Task State Change
        detail:
          clusterArn:
            - arn:aws:ecs:ap-northeast-2:xxxxxxxxxxxx:cluster/svcpeaking-cluster
      Name: !Sub ${LogicalNamePrefix}-ECSTask
      State: !Ref ECSTaskEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForKMS:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for KMS created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.kms
        detail-type: 
          - KMS CMK Rotations
          - KMS Imported Key Material Expiration
          - KMS CMK Deletion
      Name: !Sub ${LogicalNamePrefix}-KMS
      State: !Ref KMSEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForManagementConsole:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Management Console created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.signin
        detail-type: 
          - AWS Console Sign In via CloudTrail
      Name: !Sub ${LogicalNamePrefix}-ManagementConsole
      State: !Ref ManagementConsoleEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForTag:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Tag created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.tag
        detail-type: 
          - Tag Change on Resource
      Name: !Sub ${LogicalNamePrefix}-Tag
      State: !Ref TagEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
  EventBridgeForTrustedAdvisor:
    Type: 'AWS::Events::Rule'
    Properties: 
      Description: !Sub Rule for Trusted Advisor created by ${AWS::StackName}.
      EventPattern:
        source:
          - aws.trustedadvisor
        detail-type: 
          - Trusted Advisor Check Item Refresh Notification
      Name: !Sub ${LogicalNamePrefix}-TrustedAdvisor
      State: !Ref TrustedAdvisorEventsRule
      Targets:
        - Arn: !Ref SNSForAlertArn
          Id: SNSForAlert
#  EventBridgeForRDS:
#    Type: 'AWS::Events::Rule'
#    Properties: 
#      Description: !Sub Rule for RDS created by ${AWS::StackName}.
#      EventPattern:
#        source:
#          - aws.rds
#        detail-type: 
#          - RDS DB Cluster Event
#          - RDS DB Instance Event
#      Name: !Sub ${LogicalNamePrefix}-RDS
#      State: !Ref RDSEventsRule
#      Targets:
#        - Arn: !Ref SNSForAlertArn
#          Id: SNSForAlert
